#! /bin/sh
# /etc/init.d/iot-message

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       Script based on this:  http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting iot-message"
    cd /home/pi/iot-message

    #show introductory message, just for fun.
    sudo python clear.py
    sudo python scroll.py "Initializing" &
    sleep 3s
    sudo killall python
    sudo python clear.py

    #run it. 
    sudo python iot-message.py &
    ;;
  stop)
    echo "Stopping iot-message"
    sudo killall python

    cd /home/pi/iot-message
    
    #show bye message, just for fun.
    sudo python clear.py
    sudo python scroll.py "Bye now." &
    sleep 3s
    sudo killall python
    sudo python clear.py
    ;;
  *)
    echo "Usage: /etc/init.d/iot-message {start|stop}"
    exit 1
    ;;
esac

exit 0
